### ISSUE TITLE
Add project template to demostrate this project

### ISSUE THREAD

**Issue by Ledenel** [konstin/capybara#5]
First of all, it's a fantastic idea! I'm learning rust to make my library language-agnostic and platform-agnostic (e.g. to provide python bindings and javascript bindings (on pure browser, not on Node.js) with only one codebase.) 

I think this project is a good start for me, but the processes to publish package on npm, pypi (or rubygems) is not straightforward enough. I think an out-of-the-box support for npm, pypi and rubygems will be better. Therefore, a github project-template (or even [cookiecutter](https://github.com/cookiecutter/cookiecutter) template like a mix of https://github.com/ratson/cookiecutter-npm-package and https://github.com/audreyfeldroy/cookiecutter-pypackage) is super handy for this project. 

Do you have any plans for that? if not, I can try my best to contribute one (maybe for a long time).

**Comment by konstin** [comment]
Sorry, but this project never made it beyond a prove of concept and has effectively been dead for two years.
